#!/usr/bin/env python3
"""Run the locked OpenSLR SLR31 acquisition and curation pilot."""
from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlparse

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from audio_curation.crawler import (  # noqa: E402
    CrawlPolicy, PoliteSession, count_audio_members, download_file,
    extract_librispeech_archive, parse_openslr_page, write_json,
)
from audio_curation.pipeline import CurationPipeline  # noqa: E402

PAGE_URL = "https://www.openslr.org/31/"
ARCHIVE_NAME = "dev-clean-2.tar.gz"
ALLOWED_LICENSE = "CC BY 4.0"


def arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--work-dir", default="data/openslr31_pilot")
    parser.add_argument("--report-dir", default="experiments/results/openslr31_pilot")
    parser.add_argument("--max-clips", type=int, default=250)
    parser.add_argument("--min-delay-sec", type=float, default=5.0)
    parser.add_argument("--max-download-mb", type=int, default=600)
    parser.add_argument("--reuse-archive", action="store_true")
    return parser.parse_args()


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def render_card(report: dict) -> str:
    f = report["funnel"]
    before = report["diversity_before"]
    after = report["diversity_after"]
    return f"""# OpenSLR SLR31 acquisition pilot

Generated by `scripts/crawl_openslr.py`; values come from the adjacent JSON report.

## Source and policy

- Source: [{report['source']['identifier']}]({report['source']['page_url']})
- License stated by source: `{report['source']['license']}` (CC BY 4.0; attribution required)
- Static HTTP only; no JS browser. Every requested URL passed a live robots check.
- Effective minimum delay: {report['policy']['min_delay_sec']:.1f} seconds per host.
- Deterministic sample: first {report['policy']['max_clips']} FLAC members by archive path.

## Acquisition and curation funnel

| Stage | Count |
|---|---:|
| Source pages crawled | {f['pages_crawled']} |
| Unique archive candidates found | {f['candidate_archives_found']} |
| Selected archives available for processing | {f['archives_acquired']} |
| Archives downloaded in this invocation | {f['archives_downloaded_this_run']} |
| Archives reused from a prior verified transfer | {f['archive_reused']} |
| Audio members in selected archive | {f['candidate_audio_members']} |
| Aligned clips extracted (locked cap) | {f['clips_extracted']} |
| Clips passing quality policy | {f['clips_passing_quality']} |
| Exact duplicate clips removed | {f['exact_duplicates_removed']} |
| MFCC-LSH review candidates (not removed) | {f['near_duplicate_candidates']} |
| Clips retained | {f['clips_retained']} |

## Diversity and downstream interpretation

Observed speakers change from {before['n_speakers']} before filtering to
{after['n_speakers']} after filtering. The before/after diversity reports include
speaker balance, transcript vocabulary, sentence length, and duration. Gender, age,
and accent are unavailable in SLR31 and are deliberately not inferred from voices.

The retained Parquet manifest uses the shared `id`, `path`, and `sentence` interface
accepted by the adjacent Whisper evaluation scripts. This pilot establishes an
auditable acquisition-to-ASR path; it does **not** establish a model gain. SLR31 is
read speech rather than financial-domain training data, and any training-effect claim
requires a separate locked multi-seed intervention with paired 95% confidence intervals.
"""


def main() -> None:
    args = arguments()
    if not 1 <= args.max_clips <= 250:
        raise SystemExit("locked pilot requires --max-clips in [1, 250]")
    if args.min_delay_sec < 5:
        raise SystemExit("locked pilot forbids a delay below five seconds")

    work = Path(args.work_dir)
    report_dir = Path(args.report_dir)
    archive_path = work / "downloads" / ARCHIVE_NAME
    raw_audio = work / "raw_audio"
    work.mkdir(parents=True, exist_ok=True)
    report_dir.mkdir(parents=True, exist_ok=True)
    policy = CrawlPolicy(
        min_delay_sec=args.min_delay_sec,
        max_download_bytes=args.max_download_mb * 1_000_000,
    )
    client = PoliteSession(policy)

    page_response = client.get(PAGE_URL)
    source = parse_openslr_page(page_response.text, PAGE_URL)
    if source["identifier"] != "SLR31" or source["license"] != ALLOWED_LICENSE:
        raise RuntimeError(f"source identity/license gate failed: {source}")
    candidates = source["archives"]
    if ARCHIVE_NAME not in {item["filename"] for item in candidates}:
        raise RuntimeError(f"locked archive absent from source page: {ARCHIVE_NAME}")

    selected = next(item for item in candidates if item["filename"] == ARCHIVE_NAME)
    canonical_archive_url = f"{urlparse(PAGE_URL).scheme}://{urlparse(PAGE_URL).netloc}/resources/31/{ARCHIVE_NAME}"
    archive_urls = list(dict.fromkeys([canonical_archive_url, *selected["mirrors"]]))
    reused = args.reuse_archive and archive_path.exists()
    acquisition_errors = []
    archives_attempted = 0
    if reused:
        archive_bytes, archive_sha = archive_path.stat().st_size, sha256(archive_path)
        archives_downloaded = 0
        archive_url = canonical_archive_url
    else:
        for archive_url in archive_urls:
            archives_attempted += 1
            try:
                archive_bytes, archive_sha = download_file(client, archive_url, archive_path)
                archives_downloaded = 1
                break
            except Exception as exc:
                acquisition_errors.append({"url": archive_url, "error": f"{type(exc).__name__}: {exc}"})
        else:
            raise RuntimeError(f"all official archive endpoints failed: {acquisition_errors}")

    source_context = {
        **source, "page_url": PAGE_URL, "archive_url": archive_url,
    }
    manifest = extract_librispeech_archive(
        archive_path, raw_audio, max_clips=args.max_clips, source=source_context
    )
    raw_manifest = work / "raw_manifest.parquet"
    manifest.to_parquet(raw_manifest, index=False)
    audio_members = count_audio_members(archive_path)

    commit = subprocess.run(
        ["git", "-C", str(ROOT), "rev-parse", "HEAD"], check=True,
        capture_output=True, text=True,
    ).stdout.strip()
    curated_dir = work / "curated"
    pipeline = CurationPipeline(output_dir=curated_dir)
    filtered, curation = pipeline.run(manifest, run_metadata={
        "schema_version": 1,
        "generator": "scripts/crawl_openslr.py",
        "git_commit": commit,
        "research_plan": "CRAWL_RESEARCH_PLAN.md",
        "source_page_sha256": hashlib.sha256(page_response.content).hexdigest(),
        "archive_sha256": archive_sha,
        "archive_bytes": archive_bytes,
        "archive_reused": reused,
    })
    exact_removed = curation["deduplication"]["exact_duplicates_removed"]
    report = {
        "schema_version": 1,
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "source": {
            "identifier": source["identifier"], "page_url": PAGE_URL,
            "license": source["license"], "archive_url": archive_url,
            "archive_sha256": archive_sha, "archive_bytes": archive_bytes,
        },
        "policy": {
            "max_clips": args.max_clips, "min_delay_sec": args.min_delay_sec,
            "max_download_bytes": policy.max_download_bytes,
            "robots": client.robots_evidence(),
        },
        "funnel": {
            "pages_crawled": 1,
            "candidate_archives_found": len(candidates),
            "archive_endpoints_attempted": archives_attempted,
            "archives_acquired": 1,
            "archives_downloaded_this_run": archives_downloaded,
            "archive_reused": int(reused),
            "candidate_audio_members": audio_members,
            "clips_extracted": len(manifest),
            "clips_passing_quality": curation["quality"]["passed"],
            "exact_duplicates_removed": exact_removed,
            "near_duplicate_candidates": curation["deduplication"]["near_duplicate_candidates"],
            "clips_retained": len(filtered),
        },
        "diversity_before": curation["diversity_before"],
        "diversity_after": curation["diversity_after"],
        "acquisition_errors": acquisition_errors,
        "artifacts": {
            "raw_manifest": str(raw_manifest),
            "filtered_manifest": str(curated_dir / "filtered_manifest.parquet"),
            "curation_report": str(curated_dir / "curation_report.json"),
        },
    }
    write_json(report_dir / "data_card.json", report)
    (report_dir / "DATA_CARD.md").write_text(render_card(report))
    print(json.dumps(report["funnel"], indent=2))


if __name__ == "__main__":
    main()
