#!/usr/bin/env python3
"""Render the controlled deduplication benchmark JSON as Markdown."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input",
        default="experiments/results/dedup_validation/summary.json",
    )
    parser.add_argument(
        "--output",
        default="experiments/results/dedup_validation/summary.md",
    )
    args = parser.parse_args()
    report = json.loads(Path(args.input).read_text())
    labels = {
        "candidate_recall": "LSH candidate recall",
        "candidate_precision": "LSH candidate precision",
        "final_recall": "Final recall",
        "final_precision": "Final precision",
        "final_specificity": "Final specificity",
    }
    lines = [
        "# Controlled deduplication validation",
        "",
        "| Metric | Estimate (Wilson 95% CI) | Numerator / denominator |",
        "|---|---:|---:|",
    ]
    for key, label in labels.items():
        item = report[key]
        interval = item["wilson_95_ci"]
        lines.append(
            f"| {label} | {item['estimate'] * 100:.1f}% "
            f"({interval[0] * 100:.1f}–{interval[1] * 100:.1f}%) | "
            f"{item['numerator']} / {item['denominator']} |"
        )
    lines.extend([
        "",
        f"Positive pairs: {report['n_positive_pairs']}; "
        f"negative pairs: {report['n_negative_pairs']}.",
        "",
        f"> {report['claim_boundary']}",
        "",
        "The observed recall and precision do not support automatic "
        "near-duplicate removal. Exact-hash removal remains separate.",
        "",
        "Generated by `scripts/render_dedup_validation.py` from `summary.json`.",
        "",
    ])
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))


if __name__ == "__main__":
    main()
